version: '3'
services:
  mysql-hackingrio:
    image: mysql:latest
    container_name: mysql-hackingrio
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    volumes:
      - ./database-mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    networks:
      - hackingrio

networks:
  hackingrio: {}

